# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vctrBILPDRWv9R7cY4ayITJLPU78Mwft
"""

# Download Dataset: https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

# ============================================================
# Retail Sales Data Analysis Project
# Requirements:
# Data Cleaning
# EDA
# GroupBy
# Feature Engineering
# Pivot Table
# Correlation
# Visualization
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------
df = pd.read_csv("retail_sales_dataset.csv")

print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.head())
print(df.info())

# ------------------------------------------------------------
# Rename Columns
# ------------------------------------------------------------
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# ------------------------------------------------------------
# Missing Values
# ------------------------------------------------------------
print("\nMissing Values")
print(df.isnull().sum())

# Fill numerical columns
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

# Fill categorical columns
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna("Unknown")

# ------------------------------------------------------------
# Remove Duplicates
# ------------------------------------------------------------
print("\nDuplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

# ------------------------------------------------------------
# Convert Date
# ------------------------------------------------------------
date_cols = [c for c in df.columns if "date" in c]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

# ------------------------------------------------------------
# Clean Text Columns
# ------------------------------------------------------------
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip().str.title()

# ------------------------------------------------------------
# Summary Statistics
# ------------------------------------------------------------
print("\nSummary Statistics")
print(df.describe(include="all"))

# ------------------------------------------------------------
# Value Counts
# ------------------------------------------------------------
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(df[col].value_counts())

# ------------------------------------------------------------
# Feature Engineering
# ------------------------------------------------------------
if "total_amount" in df.columns:

    df["amount_category"] = pd.cut(
        df["total_amount"],
        bins=[0,100,500,1000,100000],
        labels=["Low","Medium","High","Premium"]
    )

if len(date_cols)>0:

    date = date_cols[0]

    df["year"] = df[date].dt.year
    df["month"] = df[date].dt.month
    df["day_name"] = df[date].dt.day_name()

# ------------------------------------------------------------
# Filtering
# ------------------------------------------------------------
if "total_amount" in df.columns:
    high_sales = df[df["total_amount"] > 500]
    print("\nHigh Sales Records")
    print(high_sales.head())

# ------------------------------------------------------------
# GroupBy Analysis
# ------------------------------------------------------------
cat_cols = df.select_dtypes(include="object").columns.tolist()

num_cols = df.select_dtypes(include=np.number).columns.tolist()

if len(cat_cols)>0 and len(num_cols)>0:

    group = (
        df.groupby(cat_cols[0])[num_cols[0]]
        .agg(["count","sum","mean","min","max"])
        .sort_values("sum",ascending=False)
    )

    print(group)

# ------------------------------------------------------------
# Pivot Table
# ------------------------------------------------------------
if len(cat_cols)>=2 and len(num_cols)>0:

    pivot = pd.pivot_table(
        df,
        values=num_cols[0],
        index=cat_cols[0],
        columns=cat_cols[1],
        aggfunc="sum",
        fill_value=0
    )

    print("\nPivot Table")
    print(pivot)

# ------------------------------------------------------------
# Correlation
# ------------------------------------------------------------
corr = df.select_dtypes(include=np.number).corr()

print("\nCorrelation Matrix")
print(corr)

# ------------------------------------------------------------
# Visualization 1
# ------------------------------------------------------------
if len(cat_cols)>0 and len(num_cols)>0:

    group = (
        df.groupby(cat_cols[0])[num_cols[0]]
        .sum()
        .sort_values(ascending=False)
    )

    plt.figure(figsize=(10,5))
    group.plot(kind="bar")
    plt.title("Category-wise Sales")
    plt.ylabel("Total")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# Visualization 2
# ------------------------------------------------------------
if len(num_cols)>0:

    plt.figure(figsize=(8,5))
    plt.hist(df[num_cols[0]], bins=20)
    plt.title("Distribution")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# Visualization 3
# ------------------------------------------------------------
if len(date_cols)>0 and "total_amount" in df.columns:

    monthly = (
        df.groupby("month")["total_amount"]
        .sum()
    )

    plt.figure(figsize=(10,5))
    monthly.plot(marker='o')
    plt.title("Monthly Sales")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# Outlier Detection
# ------------------------------------------------------------
if "total_amount" in df.columns:

    Q1 = df["total_amount"].quantile(.25)
    Q3 = df["total_amount"].quantile(.75)

    IQR = Q3-Q1

    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    outliers = df[
        (df["total_amount"]<lower) |
        (df["total_amount"]>upper)
    ]

    print("\nOutliers:", len(outliers))

# ------------------------------------------------------------
# Save Cleaned Dataset
# ------------------------------------------------------------
df.to_csv("cleaned_retail_sales.csv", index=False)

print("\nCleaned dataset saved successfully.")
print("Analysis Completed.")