# -*- coding: utf-8 -*-
"""Multi-Algorithm Recommendation System Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3AXb5SUxAMaiaWcd_HZp9Y1RT_zRNze
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import Ridge, LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                             accuracy_score, precision_score, recall_score, f1_score,
                             confusion_matrix, silhouette_score)

# ==========================================
# STEP 1: LOAD / GENERATE DATASET
# ==========================================
def generate_data(n=1000):
    np.random.seed(42)
    data = {
        'User_ID': range(1, n + 1),
        'Product_Category': np.random.choice(['Electronics', 'Clothing', 'Home', 'Books'], n),
        'Price': np.random.uniform(10, 500, n),
        'Number_of_Views': np.random.randint(1, 50, n),
        'Time_Spent': np.random.uniform(1, 30, n),
        'Previous_Purchases': np.random.randint(0, 20, n),
        'Cart_Status': np.random.choice([0, 1], n, p=[0.7, 0.3]),
        'Rating': np.random.uniform(1, 5, n),
        'Purchase_Status': np.random.choice([0, 1], n, p=[0.8, 0.2])
    }
    return pd.DataFrame(data)

df = generate_data(1000)
print("Dataset Sample:\n", df.head())

# ==========================================
# STEP 2: PREPROCESSING
# ==========================================
# 1. Encode Categorical Data
le = LabelEncoder()
df['Product_Category'] = le.fit_transform(df['Product_Category'])

# 2. Define Features
# For Regression and Classification, we use similar features
features = ['Product_Category', 'Price', 'Number_of_Views', 'Time_Spent', 'Previous_Purchases', 'Cart_Status']

X = df[features]
y_reg = df['Rating']             # Target for Regression
y_clf = df['Purchase_Status']    # Target for Classification

# 3. Scaling (Essential for Ridge, Logistic, and K-Means)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Train-Test Split
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_scaled, y_reg, test_size=0.2, random_state=42)
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_scaled, y_clf, test_size=0.2, random_state=42)

# ==========================================
# STEP 3: RIDGE REGRESSION (Predict Rating)
# ==========================================
print("\n--- Training Ridge Regression ---")
ridge = Ridge()
param_grid_reg = {'alpha': [0.01, 0.1, 1, 10, 100]}
grid_reg = GridSearchCV(ridge, param_grid_reg, cv=5)
grid_reg.fit(X_train_reg, y_train_reg)

best_ridge = grid_reg.best_estimator_
y_pred_reg = best_ridge.predict(X_test_reg)

mae = mean_absolute_error(y_test_reg, y_pred_reg)
rmse = np.sqrt(mean_squared_error(y_test_reg, y_pred_reg))
r2 = r2_score(y_test_reg, y_pred_reg)

# ==========================================
# STEP 4: LOGISTIC REGRESSION (Predict Purchase)
# ==========================================
print("--- Training Logistic Regression ---")
log_reg = LogisticRegression()
param_grid_clf = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['liblinear', 'lbfgs'],
    'max_iter': [200]
}
grid_clf = GridSearchCV(log_reg, param_grid_clf, cv=5)
grid_clf.fit(X_train_clf, y_train_clf)

best_log = grid_clf.best_estimator_
y_pred_clf = best_log.predict(X_test_clf)

acc = accuracy_score(y_test_clf, y_pred_clf)
prec = precision_score(y_test_clf, y_pred_clf, zero_division=0)
rec = recall_score(y_test_clf, y_pred_clf, zero_division=0)
f1 = f1_score(y_test_clf, y_pred_clf, zero_division=0)

# ==========================================
# STEP 5: K-MEANS CLUSTERING (Segment Customers)
# ==========================================
print("--- Training K-Means Clustering ---")
# Use behavior-related columns
cluster_features = ['Number_of_Views', 'Previous_Purchases', 'Time_Spent', 'Price']
X_clust = scaler.fit_transform(df[cluster_features])

# Elbow Method to find K
inertia = []
K_range = range(2, 7)
for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_clust)
    inertia.append(kmeans.inertia_)

# Final K-Means with k=4 (as per case study suggestion)
kmeans_final = KMeans(n_clusters=4, random_state=42, n_init=10)
# Changed kmeans_final.fit_transform(X_clust).argmax(axis=1)
# to kmeans_final.fit_predict(X_clust) to correctly assign clusters.
df['Cluster'] = kmeans_final.fit_predict(X_clust)
sil_score = silhouette_score(X_clust, kmeans_final.labels_)

# ==========================================
# STEP 6: COMPARISON TABLE & VISUALIZATION
# ==========================================
results = {
    "ML Task": ["Regression", "Classification", "Clustering"],
    "Algorithm": ["Ridge Regression", "Logistic Regression", "K-Means"],
    "Best Metric": [f"R2: {r2:.4f}", f"F1: {f1:.4f}", f"Silhouette: {sil_score:.4f}"],
    "Business Use": ["Recommend highly rated products", "Target likely buyers", "Segment customers"]
}

results_df = pd.DataFrame(results)
print("\n", results_df)

# Visualizing Elbow Method
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(K_range, inertia, marker='o')
plt.title('Elbow Method (Inertia)')
plt.xlabel('Number of Clusters')

# Visualizing Confusion Matrix
plt.subplot(1, 2, 2)
sns.heatmap(confusion_matrix(y_test_clf, y_pred_clf), annot=True, fmt='d', cmap='Blues')
plt.title('Logistic Regression Confusion Matrix')
plt.tight_layout()
plt.show()

# Final Summary Report Data
print(f"\nDetailed Regression Performance: MAE: {mae:.2f}, RMSE: {rmse:.2f}")
print(f"Detailed Classification Performance: Accuracy: {acc:.2f}, Precision: {prec:.2f}")